### PR TITLE
Feature/testing

### PR DESCRIPTION
**Pull request by pacyL2K19**
# The aim of this PR 
- Setting up testing environment
- Implement snapshot tests for the screens 
- Implement unit testing for components
- Update the Readme file

### CODE REVIEW

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️

Hello @pacyL2K19,

Good job so far, your tests are passing and I can see that you put a lot of effort in your tests, I will mention you some things that need to be improved in order to move on and also help you out with the dependency problem that you are having:

[Your dependency problem]:

1. Please delete your node_modules folder and your package-lock.json file.
2. If you run this command: npm ls babel-jest you will see that you have 2 conflicting versions from babel-jest, remove the one that uses jest-cli:
3. Go to your package.json file and remove your "jest-cli": "^27.0.6", dependency from your dependencies section.
4. Run npm install/test again and everything should work now. This problem is originated because you have a version conflict that is being installed from multiple dependencies.

Now to the required changes:

- [x] All functionalities are tested using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/), `@testing-library/react`, see the [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/testing/useReactTestingLibrary.png) from [Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106580952/). (Currently you are using enzyme and react-test-renderer).
- [x] You must have one expect per it in your tests, please fix this, it is required by Microverse, it is a good programming habit for testing and your unit tests should fail only for one reason.

Please correct those issues and send another review request, good luck, and well done so far!

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this PR. 
Unfortunately you did not address the changes requested by the previous reviewer.
- You are still not using the `@testing-library/react` package 
- You have many `expect` statements per `it` block. This is not a good way to test. If a test fails in a block with many scenarios, it will take you some time to figure out.


### Martin Afani
#### Slack: whiz25

**Review by eliasecasta — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️

Hello @pacyL2K19,

- [ ] Sorry if I was not clear but everything should be tested ONLY with @testing-library/react, you are not allowed to use jest-dom.
- [ ] What I meant with the expect inside it is that only 1 expect should exist inside an it, you had to divide your expects in multiple its instead of getting rid of them. It is fine, you still have a good amount of tests but the problem now is that you deleted the negative tests that you had previously created, please add them back again.

Everything else looks and works as expected, please correct those issues and send another review request, good luck, and well done so far!

**Comment by pacyL2K19** [comment]
Enervant !

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @pacyL2K19**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
